wandb_version: 1

dataset_path:
  desc: null
  value: dataset
batch_size:
  desc: null
  value: 8
num_epochs:
  desc: null
  value: 100
latent_dim:
  desc: null
  value: 256
hidden_dim:
  desc: null
  value: 256
output_channels:
  desc: null
  value: 3
num_layers:
  desc: null
  value: 6
learning_rate:
  desc: null
  value: 0.0002
ema_decay:
  desc: null
  value: 0.999
gradient_penalty_weight:
  desc: null
  value: 10
path_length_weight:
  desc: null
  value: 2
style_mixing_weight:
  desc: null
  value: 2
checkpoint_interval:
  desc: null
  value: 10
early_stopping_patience:
  desc: null
  value: 10
accumulate_grad_batches:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717591946
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 105
      3:
      - 16
      - 23
      4: 3.12.2
      5: 0.17.0
      6: 4.41.2
      8:
      - 4
      - 5
      13: darwin-arm64
